package io.sourcecreative.myriad.client.model.event;

public enum Events {
	CAMPAIGN_CREATED,
	CAMPAIGN_UPDATED,
	CAMPAIGN_DELETE,
	CAMPAIGN_ENABLED,
	CAMPAIGN_DISABLED,
	
	VOUCHER_ISSUED,
	VOUCHER_DISTRIBUTED,
	
	REDEMPTION_SUCCEEDED,
	REDEMPTION_FAILED,
	
	ORDER_CREATED,
	ORDER_UPDATED,
	ORDER_PAID,
	ORDER_CANCELLED;
	
}
